### PR TITLE
[ESAT-400] Add Mallard-specific CPU driver to program the TwinJet prefetcher

### PR DESCRIPTION
**Pull request by zongbox**
Add HWPF support. There is no independent device node for HWPF (TwinJet Prefetcher), it is present in CPU device node. so we use the 'hwpf-nStreams' property as compatible string like pmp does.

### CODE REVIEW

**Comment by zongbox** [comment]
I can execute the instructions successfully by hand:

1. `git clone https://github.com/sifive/freedom-devicetree-tools.git` && `cd freedom-devicetree-tools`
2. `git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +aab5f40c91c0546daf8fff60b199dbd00c839b19:
refs/remotes/pull/259/merge`
2. `git checkout --progress --force refs/remotes/pull/259/merge`

**Comment by zongbox** [comment]
Changed in v2:
 - change name to twinjet from hwpf.
 - modify the struct definition of twinjet which generated by metal_header-generator

**Comment by paul-walmsley-sifive** [comment]
Hi Zong, I looked at the changes.  I'm not sure I understand them completely. If the CPU string includes "sifive,mallard0", then as I understand it, the prefetcher is present.  Is there any way to enable this as part of a Mallard CPU driver, or something like that, so other DT params wouldn't be needed ?

**Comment by zongbox** [comment]
Changed in v3:
 - Change header generators for mallard CPU instead of TwinJet block

**Review by paul-walmsley-sifive — APPROVED** [review]

**Comment by paul-walmsley-sifive** [comment]
Hi @loiclefort @e-puerto @sifive-eblot , could you please review this one ?  thanks

**Pull request merged**
