### PR TITLE
Remove all but Metal and Bare header generators

### PR DESCRIPTION
**Pull request by nategraff-sifive**
Remove all of the tools that generate all of the secondary board support files in favor of pydevicetree-based python scripts tracked in their individual repositories:
- https://github.com/sifive/cmsis-svd-generator
- https://github.com/sifive/devicetree-overlay-generator
- https://github.com/sifive/esdk-settings-generator
- https://github.com/sifive/ldscript-generator
- https://github.com/sifive/openocdcfg-generator

### CODE REVIEW

**Comment by nategraff-sifive** [comment]
@albertchen-sifive Is there anything you'd like to be changed about the wakefiles given that we're removing all of these tools?

**Comment by albertchen-sifive** [comment]
yes, I'd like to remove the ones that were replaced with python tools https://github.com/sifive/freedom-devicetree-tools/pull/205

**Comment by nategraff-sifive** [comment]
Working on replacing the removed Wake APIs with stuff like this: https://github.com/sifive/ldscript-generator/pull/7.

Once that one (and similar ones for the other tools) are completed, api-generator-sifive can be modified to consume those APIs instead of the ones provided by the Wake rules removed by this PR.

**Comment by nategraff-sifive** [comment]
I have Wake APIs for all of the tools staged, I'm going to try my hand at making api-generator-sifive use them.

**Pull request merged**
