### PR TITLE
Add support for sifive,prci0

### PR DESCRIPTION
**Pull request by zongbox**
This PRCI is for SiFive HiFive platform. It basically supports getting the base address and size.

### CODE REVIEW

**Comment by paul-walmsley-sifive** [comment]
Hi Zong, the basic idea looks good to me, but we probably need to rename "sifive,prci0" to something that is Unmatched-specific, like "sifive,unmatched-prci0", since the PRCI implementations are different for different SoCs (Unleashed PRCI != Unmatched PRCI).   Then we probably need to modify the overlay generator to rename "sifive,prci0" for Unmatched to "sifive,unmatched-prci0"

**Review by paul-walmsley-sifive — CHANGES_REQUESTED** [review]
(See my previous comment)

**Comment by e-puerto** [comment]
@zongbox, @paul-walmsley-sifive here the PCRI definition on unleashed board.
`		prci: prci@10000000 {
			compatible = "sifive,ux00prci0";
			reg = <0x0 0x10000000 0x0 0x1000>;
			reg-names = "control";
			clocks = <&refclk>;
			#clock-cells = <1>;
		};
`
I do not know what the "ux00" prefix means, but perhaps we should use "ux01" for unmatched board ;)

**Comment by paul-walmsley-sifive** [comment]
"ux00" was probably only meant to refer to Aloe, but wound up referring to both Aloe and Almond.  So it's useless for distinguishing the two.

My suggestion about "sifive,unmatched-prci0" was rather stupid, as @e-puerto reminded me.  It should be something like "sifive,fu740-c000-prci0" instead.    For that to work, the devicetree-overlay-generator will probably need to be modified to rewrite "sifive,ux00prci0" to "sifive,fu740-c000-prci0" if it sees that the SoC is an Almond (e.g., matching on /compatible = "SiFive,FU740-C000" or whatever)

**Comment by zongbox** [comment]
Changed in v2:
 - rename the compatible string: 'sifive,fu740-c000-prci0' is for Unmatched and 'sifive,fu540-c000-prci0' is for Unleashed.
 - distinguish Unleashed and Unmatched by compatible string, then emits different register offset respectively, the PRCI memory map of Unleashed is subset of Unmatched, so we can use this same generator for them.
 - We change the macro METAL_SIFIVE_PRCI0 to METAL_SIFIVE_FU540_C000_PRCI0 or METAL_SIFIVE_FU740_C000_PRCI0 depends on the compatible string, these macro will be used to separate the implementation in PRCI driver of freedom-metal library.

**Review by paul-walmsley-sifive — APPROVED** [review]

**Comment by paul-walmsley-sifive** [comment]
Thanks Zong

**Pull request merged**
