### PR TITLE
Enabling ccache support for latency improvement  

### PR DESCRIPTION
**Pull request by bsousi5**

### CODE REVIEW

**Comment by reclusejack** [comment]
Hi @bsousi5 I've applied this patch but can't generate l2 cache init code.

The following defines are part of sifive_fu540-c000_l2 driver but not generated with this patch~

#define METAL_SIFIVE_FU540_C000_L2_2010000_BASE_ADDRESS 33619968UL
#define METAL_SIFIVE_FU540_C000_L2_0_BASE_ADDRESS 33619968UL
#define METAL_SIFIVE_FU540_C000_L2_2010000_SIZE 4096UL
#define METAL_SIFIVE_FU540_C000_L2_0_SIZE 4096UL

#define METAL_SIFIVE_FU540_C000_L2
#define METAL_SIFIVE_FU540_C000_L2_CONFIG 0UL
#define METAL_SIFIVE_FU540_C000_L2_WAYENABLE 8UL

**Comment by bsousi5** [comment]
> Hi @bsousi5 I've applied this patch but can't generate l2 cache init code.
> 
> The following defines are part of sifive_fu540-c000_l2 driver but not generated with this patch~
> 
> #define METAL_SIFIVE_FU540_C000_L2_2010000_BASE_ADDRESS 33619968UL
> #define METAL_SIFIVE_FU540_C000_L2_0_BASE_ADDRESS 33619968UL
> #define METAL_SIFIVE_FU540_C000_L2_2010000_SIZE 4096UL
> #define METAL_SIFIVE_FU540_C000_L2_0_SIZE 4096UL
> 
> #define METAL_SIFIVE_FU540_C000_L2
> #define METAL_SIFIVE_FU540_C000_L2_CONFIG 0UL
> #define METAL_SIFIVE_FU540_C000_L2_WAYENABLE 8UL

Can you give me a bit more context here. For both sifive-sifive-unleash and e76mc, the equivalent L2 #define get generated.

**Comment by reclusejack** [comment]
@bsousi5 Could you check the file ./src/drivers/sifive_fu540-c00_l2.c in freedom-metal repo?
All defines are METAL_SIFIVE_FU540_C000_L2 related. The sifive_fu540-c00_l2.o will be empty with defines of METAL_SIFIVE_CCACHE0.

**Comment by bsousi5** [comment]
Resorted to adding a separate device for ccache0, which end up needing another metal driver per, this PR https://github.com/sifive/freedom-metal/pull/181

**Pull request merged**
